### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SeongwooCheon** [OpenFAST/openfast_toolbox#10]
Hello

When I install the openfast toolbox according to the installation guide, I get this error.
I thick the cause of this error is that the versions of Python and pip do not match to install the toolbox.
How can I fix it?

![image](https://github.com/OpenFAST/openfast_toolbox/assets/77769771/f1b05641-3535-4f0a-b02c-5428d7a74c12)

**Comment by ebranlard** [comment]
Your python version seems too old, try installing a python version above 3.6
