### ISSUE TITLE
 ValueError: not enough values to unpack (expected 6, got 3) while trying to run Example_CPLambdaPitch.py

### ISSUE THREAD

**Issue by gorby217** [OpenFAST/openfast_toolbox#11]
Hi,
I'm trying to run the Example_CPLambdaPitch.py for a 2MW OpenFAST turbine model and I encounter "ValueError: not enough values to unpack (expected 6, got 3)" after the simulations are finished and when postprocessing is initiated by the script. The issue seems to be with this line:
    CP,CT,Lambda,Pitch,MaxVal,result = case_gen.CPCT_LambdaPitch(ref_dir,main_file,Lambda,Pitch,fastExe=FAST_EXE,showOutputs=False,nCores=4,TMax=10)
where the script is expecting 6 values to be returned but case_gen.CPCT_LambdaPitch seems to be returning only 3:

    return  rs, result, fig

What am I missing here?

**Comment by ebranlard** [comment]
Thanks for pointing this out, the interface was indeed updated and not the example. 
I've now updated the example, you can see how you can use "rs" (which is a ROSCOPerformance File), to get data, plot, and write a ROSCO performance file. 

I hope that helps.

**Comment by rthedin** [comment]
Closing this. Feel free to re-open if you have further issues.
