### ISSUE TITLE
AD15 converter for OF 3.0 to OF 4.0 leaves `AFAeroMod` comments

### ISSUE THREAD

**Issue by andrew-platt** [OpenFAST/openfast_toolbox#16]
In the AD15 update for OpenFAST v4.0.0, the `AFAeroMod` option was replaced with the `UA_Mod` option (in combination with other options). However, when using the converter, comments may still contain `AFAeroMod` in the comment.  For example, the following comment (line 10) is left as:
`False         CavitCheck     - Perform cavitation check? (flag) [AFAeroMod must be 1 when CavitCheck=true]`
but should be changed to
`False         CavitCheck     - Perform cavitation check? (flag) [UA_Mod must be 0 when CavitCheck=true]`

I took a look at the converter, but don't know python well enough to address this issue and make a PR.

**Comment by rthedin** [comment]
While this isn't complicated, it will only make sense for OpenFAST v > 4.0.0. Should we add tags to the openfast_toolbox releases as well? Old toolbox had tags and it was easier to match openfast and python-toolbox. See https://github.com/OpenFAST/openfast_toolbox/issues/7. This way we could add the appropriate comment to each tag.
