### ISSUE TITLE
Free vortex wake

### ISSUE THREAD

**Issue by 3sdb** [OpenFAST/openfast_toolbox#18]
hello
I tried to add olaf in aerodyn15 but it ran with an error. nNWPanels I use python package to calculate these parameters, the model is 15mw monopile type, there is no error when using the stationary wind, I suspect it is a turbulent wind problem, if you know the solution, please be sure to tell me.
best wishes
![634280909d932a0aa67a89babea716a](https://github.com/OpenFAST/openfast_toolbox/assets/156734919/8b063b74-b3c8-4de6-ad88-5548daf0a54c)

**Comment by jjonkman** [comment]
Hello @3sdb,

Which version of OpenFAST are you using?  Does upgrading to the newest release (currently OpenFAST v3.5.3) solve the issue?

Best regards,

**Comment by 3sdb** [comment]
Hello @jjonkman 
yes,the version i am currently using is 3.5.3.i just tried modifying the turblent wind domain,but the problem still persists.
best wishes

**Comment by jjonkman** [comment]
Do you have the same error if you switch from OLAF to BEM in the turbulent wind simulation?

**Comment by 3sdb** [comment]
if so, openfast works
