### ISSUE TITLE
Issue with read_discon_file

### ISSUE THREAD

**Issue by aravindvenkatachalapathy** [OpenFAST/openfast_toolbox#2]
I have been using ROSCODISCONFile function from read_discon_file. I have encountered a bug, while reading the .IN file and writing it again. It is adding 15 spaces for any strings that are there in .IN file. Beacuse of this while reading that same DISCON file again it is unable to read it because of this empty white spaces in the between the "" and throws up this error.
<img width="707" alt="image" src="https://github.com/OpenFAST/openfast_toolbox/assets/43172847/990cb7a1-6f1a-4616-ba02-c0dd8bfbebf5">
I have have been able to solve this issue by modifying line 145 in where i remove the part where it adds 15 whitespaces like this 
<img width="1130" alt="image" src="https://github.com/OpenFAST/openfast_toolbox/assets/43172847/d827e786-5f3e-4dd9-8828-e70d4600ffb4">
this seems to solve the problem while re-reading the same .IN file.

**Comment by aravindvenkatachalapathy** [comment]
Yeah the code is there just to make sure the input file look nice but my approach itself doesn't change any alignment. For your reference this is the .IN file before 
<img width="1132" alt="image" src="https://github.com/OpenFAST/openfast_toolbox/assets/43172847/a3b0fa36-b3da-4c82-b862-5e4e877a5b8f">
This is the .IN written after my approach
<img width="1015" alt="image" src="https://github.com/OpenFAST/openfast_toolbox/assets/43172847/ca854332-e045-420f-b7d0-df28d4569307">

**Comment by ebranlard** [comment]
Oh ok, I see. 
Should we just use your change and modify the final line as follows:
```python
               s+='{:20s} {}{}\n'.format(sval, sparam, comment)
```
I just think that adding those white spaces at the end of sval seems unnecessary.

**Comment by aravindvenkatachalapathy** [comment]
Yeah makes sense. And the above approach works for me, I can create a pull request with these changes if you are ok with it?

**Comment by ebranlard** [comment]
Yes, thank you so much for making a pull request!

**Comment by rthedin** [comment]
Closing this. Feel free to re-open if you have further issues.
