### ISSUE TITLE
Error experienced while running python scripts available as in the example

### ISSUE THREAD

**Issue by Pinkyutdmech** [OpenFAST/openfast_toolbox#20]
Hello,
I am running the example 3 scripts available in https://github.com/OpenFAST/openfast_toolbox/blob/353643ed917d113ec8dfd765813fef7d09752757/openfast_toolbox/fastfarm/examples/Ex3_FFarmCompleteSetup.py. 
I am trying to run step by step by providing the required user input. Now, I got an OS error.
File "d:\yaw_wake_effects\openfast_toolbox\openfast_toolbox\fastfarm\FASTFarmCaseCreation.py", line 602, in copyTurbineFilesForEachCase
    os.symlink(src, dst)
OSError: symbolic link privilege not held.

**Comment by rthedin** [comment]
This is an `OSError`, not an openfast_toolbox error: `OSError: symbolic link privilege not held.`
A quick Google search on this error reveals several potential sources and possible solutions.
