### ISSUE TITLE
mlife

### ISSUE THREAD

**Issue by LIUYUXIN-SA** [OpenFAST/openfast_toolbox#6]
When I run mlife, I always get the following error, I want to ask if the matlab version and the function version are not compatible (I use Matlab2020b), what version should I use to open or solve the problem?
错误使用 rainflow 输入参数太多。出错

**Comment by jjonkman** [comment]
MLife is not part of the OpenFAST Toolbox and it looks like you asked the same question in https://github.com/OpenFAST/openfast/issues/2029.  I'll close this misplaced duplicate.
