### ISSUE TITLE
pytest gives 34 errors

### ISSUE THREAD

**Issue by AdrianEolion** [OpenFAST/openfast_toolbox#8]
Hello,

I am trying to install openfast_toolbox. I have done everything the installation guide says. When I try to run the last step, pytest, python gives me the same error 34 times. It does not find the openfast_toolbox.common module. What can i do to fix this?

=============================================== test session starts ================================================
platform linux -- Python 3.10.13, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/e720/OpenFAST/openfast_toolbox
collected 0 items / 36 errors                                                                                      

====================================================== ERRORS ======================================================
______________________ ERROR collecting openfast_toolbox/aeroacoustics/tests/test_aa_tools.py ______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/aeroacoustics/tests/test_aa_tools.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________ ERROR collecting openfast_toolbox/aeroacoustics/tests/test_run_Examples.py ____________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/aeroacoustics/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/airfoils/tests/test_polar_interp.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/airfoils/tests/test_polar_interp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_______________________ ERROR collecting openfast_toolbox/airfoils/tests/test_polar_manip.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/airfoils/tests/test_polar_manip.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/airfoils/tests/test_polar_params.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/airfoils/tests/test_polar_params.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
___________________ ERROR collecting openfast_toolbox/airfoils/tests/test_polar_subfunctions.py ____________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/airfoils/tests/test_polar_subfunctions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/airfoils/tests/test_run_Examples.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/airfoils/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
___________________ ERROR collecting openfast_toolbox/case_generation/tests/test_run_Examples.py ___________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/case_generation/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
________________________ ERROR collecting openfast_toolbox/converters/tests/test_K_BD_H2.py ________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/converters/tests/test_K_BD_H2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_______________________ ERROR collecting openfast_toolbox/converters/tests/test_beamprops.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/converters/tests/test_beamprops.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________ ERROR collecting openfast_toolbox/converters/tests/test_hawc2ToBeamDyn.py _____________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/converters/tests/test_hawc2ToBeamDyn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_____________________ ERROR collecting openfast_toolbox/converters/tests/test_run_Examples.py ______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/converters/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/fastfarm/tests/test_run_Examples.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/fastfarm/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/fastfarm/tests/test_turbsimExtent.py ______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/fastfarm/tests/test_turbsimExtent.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
__________________________ ERROR collecting openfast_toolbox/io/tests/helpers_for_test.py __________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/helpers_for_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________________ ERROR collecting openfast_toolbox/io/tests/test_bladed.py _____________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_bladed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________________ ERROR collecting openfast_toolbox/io/tests/test_csv.py ______________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_csv.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
__________________________ ERROR collecting openfast_toolbox/io/tests/test_fast_input.py ___________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_fast_input.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
________________________ ERROR collecting openfast_toolbox/io/tests/test_fast_input_deck.py ________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_fast_input_deck.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/io/tests/test_fast_linearization.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_fast_linearization.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
__________________________ ERROR collecting openfast_toolbox/io/tests/test_fast_output.py __________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_fast_output.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_________________________ ERROR collecting openfast_toolbox/io/tests/test_fast_summary.py __________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_fast_summary.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_____________________________ ERROR collecting openfast_toolbox/io/tests/test_flex.py ______________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_flex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_____________________________ ERROR collecting openfast_toolbox/io/tests/test_hawc.py ______________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_hawc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________________ ERROR collecting openfast_toolbox/io/tests/test_mannbox.py ____________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_mannbox.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________________ ERROR collecting openfast_toolbox/io/tests/test_parquet.py ____________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_parquet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_________________________ ERROR collecting openfast_toolbox/io/tests/test_run_Examples.py __________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________________ ERROR collecting openfast_toolbox/io/tests/test_turbsim.py ____________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_turbsim.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________________ ERROR collecting openfast_toolbox/io/tests/test_vtk.py ______________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_vtk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_____________________________ ERROR collecting openfast_toolbox/io/tests/test_yaml.py ______________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/io/tests/test_yaml.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
___________________ ERROR collecting openfast_toolbox/linearization/tests/test_campbell_data.py ____________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/linearization/tests/test_campbell_data.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
______________________ ERROR collecting openfast_toolbox/linearization/tests/test_modesID.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/linearization/tests/test_modesID.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
___________________ ERROR collecting openfast_toolbox/linearization/tests/test_modesVizBinary.py ___________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/linearization/tests/test_modesVizBinary.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
____________________ ERROR collecting openfast_toolbox/linearization/tests/test_run_Examples.py ____________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/linearization/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
_______________________ ERROR collecting openfast_toolbox/postpro/tests/test_run_Examples.py _______________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/postpro/tests/test_run_Examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
__________________________ ERROR collecting openfast_toolbox/tools/tests/test_fatigue.py ___________________________
ImportError while importing test module '/home/e720/OpenFAST/openfast_toolbox/openfast_toolbox/tools/tests/test_fatigue.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../mambaforge/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openfast_toolbox/__init__.py:3: in <module>
    from openfast_toolbox.common import *
E   ModuleNotFoundError: No module named 'openfast_toolbox.common'
============================================= short test summary info ==============================================
ERROR openfast_toolbox/aeroacoustics/tests/test_aa_tools.py
ERROR openfast_toolbox/aeroacoustics/tests/test_run_Examples.py
ERROR openfast_toolbox/airfoils/tests/test_polar_interp.py
ERROR openfast_toolbox/airfoils/tests/test_polar_manip.py
ERROR openfast_toolbox/airfoils/tests/test_polar_params.py
ERROR openfast_toolbox/airfoils/tests/test_polar_subfunctions.py
ERROR openfast_toolbox/airfoils/tests/test_run_Examples.py
ERROR openfast_toolbox/case_generation/tests/test_run_Examples.py
ERROR openfast_toolbox/converters/tests/test_K_BD_H2.py
ERROR openfast_toolbox/converters/tests/test_beamprops.py
ERROR openfast_toolbox/converters/tests/test_hawc2ToBeamDyn.py
ERROR openfast_toolbox/converters/tests/test_run_Examples.py
ERROR openfast_toolbox/fastfarm/tests/test_run_Examples.py
ERROR openfast_toolbox/fastfarm/tests/test_turbsimExtent.py
ERROR openfast_toolbox/io/tests/helpers_for_test.py
ERROR openfast_toolbox/io/tests/test_bladed.py
ERROR openfast_toolbox/io/tests/test_csv.py
ERROR openfast_toolbox/io/tests/test_fast_input.py
ERROR openfast_toolbox/io/tests/test_fast_input_deck.py
ERROR openfast_toolbox/io/tests/test_fast_linearization.py
ERROR openfast_toolbox/io/tests/test_fast_output.py
ERROR openfast_toolbox/io/tests/test_fast_summary.py
ERROR openfast_toolbox/io/tests/test_flex.py
ERROR openfast_toolbox/io/tests/test_hawc.py
ERROR openfast_toolbox/io/tests/test_mannbox.py
ERROR openfast_toolbox/io/tests/test_parquet.py
ERROR openfast_toolbox/io/tests/test_run_Examples.py
ERROR openfast_toolbox/io/tests/test_turbsim.py
ERROR openfast_toolbox/io/tests/test_vtk.py
ERROR openfast_toolbox/io/tests/test_yaml.py
ERROR openfast_toolbox/linearization/tests/test_campbell_data.py
ERROR openfast_toolbox/linearization/tests/test_modesID.py
ERROR openfast_toolbox/linearization/tests/test_modesVizBinary.py
ERROR openfast_toolbox/linearization/tests/test_run_Examples.py
ERROR openfast_toolbox/postpro/tests/test_run_Examples.py
ERROR openfast_toolbox/tools/tests/test_fatigue.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 36 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 36 errors in 0.38s ================================================

**Comment by ebranlard** [comment]
Hi, 
I cannot reproduce your error. 
Make sure `python -m pip install -e .`  worked successfully. 
Instead of pytest, you can also do: `python -m unittest` 
I'm wondering if it's because you have two `python` commands, like a python and a `python3`. I'm not sure which one pytest is picking up. 
I hope that helps,

Emmanuel

**Comment by AdrianEolion** [comment]
Hi, I reinstalled my Ubuntu system to make things easier. After that the first thing I did was install the toolbox. For some reason it does not pass the tests using pytest. I am using python3 from Ubuntu 22.04.4 LTS, so there is no conflict with a second python version. 
Also ran some examples and they seem to work correctly. 
I don't know why pytest doesn't work. But I least I got to run the examples. 
Thank you very much!

**Comment by ebranlard** [comment]
Thanks for the update. Out of curiosity,  have you tried `python -m unittest` ?
It's good if the examples run.

**Comment by AdrianEolion** [comment]
Yes, it does run 89 tests and gives 0 errors.

Thanks you.

**Comment by ebranlard** [comment]
Great, maybe we should recommend that, there might be something off with pytest picking up the wrong python version

**Comment by rthedin** [comment]
Hey @ebranlard, I'm seeing the same error as originally reported here. It is picking up the correct python but it still fails, complaining that it can't find `openfast_toolbox.common`. I can launch the same `python` and just run `from openfast_toolbox.common import *` successfully.

More details: I did install using `python -m pip install -e .` and `python -m unittest` also fails completely. Everything seems to be working as it should, it just doesn't pass the tests.
