### ISSUE TITLE
Writing HD Driver file with openfast-toolbox 

### ISSUE THREAD

**Issue by MaximilienAndre** [OpenFAST/openfast_toolbox#9]
Hi, I have encountered issues when trying to write HD-Driver file with the python toolbox. I try to read the input file for Hydrodyn driver from `r-test\modules\hydrodyn\hd_5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth` using the FAST Input Files class but the lines where several numbers are set like the following read only one number : 

`1.0   2.0  -3.0  0.0  0.0  0.0    uPRPInSteady         - PRP Steady-state disp.`

Example : 
INPUT 
```
from openfast_toolbox.io import FASTInputFile
hdDriverFile = "hd_driver.dat"
hdd = FASTInputFile(hdDriverFile)
print(hdd['uPRPInSteady'])
```
OUTPUT 
`1.0`

I believe the fix would be to add this input names to the table reading list in FASTInputFile but I could not figure out the logic of it. 

I am using OpenFAST release 3.5.1 with associated toolbox and drivers.

**Comment by ebranlard** [comment]
Hi, you can use commas in between the numerical values oif your input file , I think it will work.

**Comment by MaximilienAndre** [comment]
Dear Emmanuel, 
Thank you for the suggestion, it worked and I could read, write an launch files with the hydrodyn driver. 

The new file line looks like: 
`0.0 ,  0.0 ,  0.0 , 0.0 , 0.0 , 0.0    uPRPInSteady         - PRP Steady-state `
and the code output is :
`[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]`
Regards

**Comment by ebranlard** [comment]
Perfect! Thanks
